apiVersion: v1
kind: Pod
metadata:
  name: bionemo-debug
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    primary_container_name: f3a3a97917dcf4c58b58-f4vl3keq-3
  creationTimestamp: "2024-07-01T14:24:20Z"
  labels:
    domain: development
    execution-id: f3a3a97917dcf4c58b58
    interruptible: "false"
    node-id: unionaiworkspacevscodeworkspace
    organization: dogfood
    project: default
    shard-key: "20"
    task-name: unionai-workspace-vscode-workspace
    workflow-name: flytegen-unionai-workspace-vscode-workspace
  namespace: default-development
  resourceVersion: "183012742"
  uid: 58323594-4724-4ce1-aa63-450b9ac2a716
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: flyte.org/node-role
            operator: In
            values:
            - worker
          - key: eks.amazonaws.com/capacityType
            operator: In
            values:
            - ON_DEMAND
  containers:
  - command: ["/bin/sh"]
    args: ["-c", "pyflyte-execute --inputs s3://union-cloud-oc-staging-dogfood/metadata/propeller/default-development-f3a3a97917dcf4c58b58/unionaiworkspacevscodeworkspace/data/inputs.pb --output-prefix s3://union-cloud-oc-staging-dogfood/metadata/propeller/default-development-f3a3a97917dcf4c58b58/unionaiworkspacevscodeworkspace/data/3 --raw-output-data-prefix s3://union-cloud-oc-staging-dogfood/ex/f3a3a97917dcf4c58b58-f4vl3keq-3 --checkpoint-path s3://union-cloud-oc-staging-dogfood/ex/f3a3a97917dcf4c58b58-f4vl3keq-3/_flytecheckpoints --prev-checkpoint s3://union-cloud-oc-staging-dogfood/py/f3a3a97917dcf4c58b58-f4vl3keq-2/_flytecheckpoints --resolver unionai.workspace._vscode.resolver -- workspace"]
    # - pyflyte-execute
    # - --inputs
    # - s3://union-cloud-oc-staging-dogfood/metadata/propeller/default-development-f3a3a97917dcf4c58b58/unionaiworkspacevscodeworkspace/data/inputs.pb
    # - --output-prefix
    # - s3://union-cloud-oc-staging-dogfood/metadata/propeller/default-development-f3a3a97917dcf4c58b58/unionaiworkspacevscodeworkspace/data/3
    # - --raw-output-data-prefix
    # - s3://union-cloud-oc-staging-dogfood/ex/f3a3a97917dcf4c58b58-f4vl3keq-3
    # - --checkpoint-path
    # - s3://union-cloud-oc-staging-dogfood/ex/f3a3a97917dcf4c58b58-f4vl3keq-3/_flytecheckpoints
    # - --prev-checkpoint
    # - s3://union-cloud-oc-staging-dogfood/py/f3a3a97917dcf4c58b58-f4vl3keq-2/_flytecheckpoints
    # - --resolver
    # - unionai.workspace._vscode.resolver
    # - --
    # - workspace
    env:
    - name: FLYTE_INTERNAL_EXECUTION_WORKFLOW
      value: default:development:.flytegen.unionai.workspace._vscode.workspace
    - name: FLYTE_INTERNAL_EXECUTION_ID
      value: f3a3a97917dcf4c58b58
    - name: FLYTE_INTERNAL_EXECUTION_PROJECT
      value: default
    - name: FLYTE_INTERNAL_EXECUTION_DOMAIN
      value: development
    - name: FLYTE_ATTEMPT_NUMBER
      value: "3"
    - name: FLYTE_INTERNAL_TASK_PROJECT
      value: default
    - name: FLYTE_INTERNAL_TASK_DOMAIN
      value: development
    - name: FLYTE_INTERNAL_TASK_NAME
      value: unionai.workspace._vscode.workspace
    - name: FLYTE_INTERNAL_TASK_VERSION
      value: bionemo-workspace-YvjAbUhZbYwJUZkNZnYf
    - name: FLYTE_INTERNAL_PROJECT
      value: default
    - name: FLYTE_INTERNAL_DOMAIN
      value: development
    - name: FLYTE_INTERNAL_NAME
      value: unionai.workspace._vscode.workspace
    - name: FLYTE_INTERNAL_VERSION
      value: bionemo-workspace-YvjAbUhZbYwJUZkNZnYf
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: us-east-2
    - name: AWS_REGION
      value: us-east-2
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::356633062068:role/oc-staging-dogfood-userflyterole
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: docker.io/unionbio/bionemo:sfbwGKADqch_TtB_O2fggQ
    imagePullPolicy: IfNotPresent
    name: f3a3a97917dcf4c58b58-f4vl3keq-3
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 4Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /union-persistent-data
      name: union-persistent-data-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-f9fzx
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-105-7-64.us-east-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: flyte.org/node-role
    operator: Equal
    value: worker
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  - hostPath:
      path: /data/union-persistent
      type: Directory
    name: union-persistent-data-volume
  - name: kube-api-access-f9fzx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace