[tool.poetry]
name = "unionbio"
version = "0.1.1"
description = ""
authors = ["pryce-turner <pryce.turner@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
flytekit = "^1.12.0"
imagespec-fast-builder = "0.0.33"
docker = "<7.0.0"
requests = "2.31.0"
flytekitplugins-envd = "^1.12.3"
streamlit = "^1.36.0"
union = {extras = ["byoc"], version = "^0.1.66"}

[tool.poetry.scripts]
image-builder = "images:build"
test-image-builder = "images:build_test"
main-tests = "tests.runner:test_main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
