[tool.poetry]
name = "unionbio"
version = "0.1.0"
description = ""
authors = ["pryce-turner <pryce.turner@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
